server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

springdoc:
  packagesToScan: com.sandpit.ds.inventory

management:
  tracing:
    sampling:
      probability: 1.0